spring.application.name=lab_sample_management_backend
spring.datasource.url=jdbc:mysql://localhost:3306/labsamples
spring.datasource.username=root
spring.datasource.password=Dnsrijon_25
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true